# Generated by Django 4.1.6 on 2023-02-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
    ]
